import bcrypt from "bcryptjs";import jwt from "jsonwebtoken";import User from "../models/User.js";import {createDataKey,wrapDataKey} from "../utils/crypto.js";import {publicId} from "../utils/ids.js";import {generateOtp,makeOtpRecord,sameOtp} from "../utils/otp.js";import {sendOtpEmail} from "../services/emailjs.js";
const safe=u=>({id:u.publicId,name:u.name,email:u.email,createdAt:u.createdAt,emailVerified:u.emailVerified});
const token=u=>jwt.sign({userId:u._id.toString(),publicId:u.publicId},process.env.JWT_SECRET,{expiresIn:"7d"});
const validEmail=e=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e);
async function issueVerifyOtp(u){const now=Date.now();if(u.otpLastSentAt&&now-u.otpLastSentAt.getTime()<30000)throw Object.assign(new Error("Please wait 30 seconds before requesting another OTP"),{status:429});const otp=generateOtp(),rec=makeOtpRecord(otp);u.otpHash=rec.hash;u.otpSalt=rec.salt;u.otpExpiresAt=new Date(now+5*60*1000);u.otpAttempts=0;u.otpLastSentAt=new Date(now);await u.save();try{await sendOtpEmail({to:u.email,name:u.name,otp,type:"verify"})}catch(e){u.otpHash=null;u.otpSalt=null;u.otpExpiresAt=null;await u.save();throw e}}
export async function register(req,res){const {name,email,password}=req.body;if(!name||!email||!password)return res.status(400).json({message:"Name, email and password are required"});if(password.length<8)return res.status(400).json({message:"Password must be at least 8 characters"});const e=email.toLowerCase().trim();if(!validEmail(e))return res.status(400).json({message:"Enter a valid email address"});const existing=await User.findOne({email:e});if(existing){if(!existing.emailVerified){try{await issueVerifyOtp(existing)}catch(err){return res.status(err.status||500).json({message:err.message})}return res.status(200).json({needsVerification:true,email:e,message:"A verification OTP was sent to your email"})}return res.status(409).json({message:"Email already registered"})}const u=await User.create({publicId:publicId("usr"),name:name.trim(),email:e,passwordHash:await bcrypt.hash(password,12),wrappedDataKey:wrapDataKey(createDataKey())});try{await issueVerifyOtp(u)}catch(err){await User.deleteOne({_id:u._id});return res.status(err.status||500).json({message:err.message})}res.status(201).json({needsVerification:true,email:e,message:"A verification OTP was sent to your email"})}
export async function verifyEmail(req,res){const {email,otp}=req.body,e=email?.toLowerCase().trim(),u=await User.findOne({email:e});if(!u||u.emailVerified)return res.status(400).json({message:"Invalid or expired verification code"});if(!/^\d{6}$/.test(otp||""))return res.status(400).json({message:"Enter the 6-digit OTP"});if(!u.otpExpiresAt||u.otpExpiresAt.getTime()<Date.now())return res.status(400).json({message:"OTP expired. Request a new code"});if(u.otpAttempts>=5)return res.status(429).json({message:"Too many attempts. Request a new OTP"});u.otpAttempts+=1;if(!sameOtp(otp,u.otpHash,u.otpSalt)){await u.save();return res.status(400).json({message:"Incorrect OTP"})}u.emailVerified=true;u.otpHash=null;u.otpSalt=null;u.otpExpiresAt=null;u.otpAttempts=0;await u.save();res.json({token:token(u),user:safe(u)})}
export async function resendOtp(req,res){const e=req.body.email?.toLowerCase().trim(),u=await User.findOne({email:e});if(!u||u.emailVerified)return res.json({message:"If the account needs verification, a new OTP has been sent"});try{await issueVerifyOtp(u);res.json({message:"A new OTP was sent"})}catch(err){res.status(err.status||500).json({message:err.message})}}
export async function login(req,res){const {email,password}=req.body,u=await User.findOne({email:email?.toLowerCase().trim()});if(!u||!(await bcrypt.compare(password||"",u.passwordHash)))return res.status(401).json({message:"Invalid email or password"});if(!u.emailVerified)return res.status(403).json({message:"Please verify your email before signing in",needsVerification:true,email:u.email});res.json({token:token(u),user:safe(u)})}
async function issueResetOtp(u){const now=Date.now();if(u.resetOtpLastSentAt&&now-u.resetOtpLastSentAt.getTime()<30000)throw Object.assign(new Error("Please wait 30 seconds before requesting another OTP"),{status:429});const otp=generateOtp(),rec=makeOtpRecord(otp);u.resetOtpHash=rec.hash;u.resetOtpSalt=rec.salt;u.resetOtpExpiresAt=new Date(now+5*60*1000);u.resetOtpAttempts=0;u.resetOtpLastSentAt=new Date(now);await u.save();try{await sendOtpEmail({to:u.email,name:u.name,otp,type:"reset"})}catch(e){u.resetOtpHash=null;u.resetOtpSalt=null;u.resetOtpExpiresAt=null;await u.save();throw e}}
export async function forgotPassword(req,res){const e=req.body.email?.toLowerCase().trim(),u=await User.findOne({email:e});if(!u)return res.json({message:"If an account exists for that email, a reset OTP was sent"});try{await issueResetOtp(u);res.json({message:"If an account exists for that email, a reset OTP was sent",email:e})}catch(err){res.status(err.status||500).json({message:err.message})}}
export async function resetPassword(req,res){const {email,otp,password}=req.body,e=email?.toLowerCase().trim(),u=await User.findOne({email:e});if(!u||!u.resetOtpHash)return res.status(400).json({message:"Invalid or expired reset code"});if(password?.length<8)return res.status(400).json({message:"Password must be at least 8 characters"});if(!u.resetOtpExpiresAt||u.resetOtpExpiresAt.getTime()<Date.now())return res.status(400).json({message:"OTP expired. Request a new code"});if(u.resetOtpAttempts>=5)return res.status(429).json({message:"Too many attempts. Request a new OTP"});u.resetOtpAttempts+=1;if(!sameOtp(otp,u.resetOtpHash,u.resetOtpSalt)){await u.save();return res.status(400).json({message:"Incorrect OTP"})}u.passwordHash=await bcrypt.hash(password,12);u.resetOtpHash=null;u.resetOtpSalt=null;u.resetOtpExpiresAt=null;u.resetOtpAttempts=0;await u.save();res.json({message:"Password reset successfully"})}
export async function me(req,res){res.json({user:safe(req.user)})}
