import Chat from "../models/Chat.js";import {decryptText,encryptText,unwrapDataKey} from "../utils/crypto.js";import {publicId} from "../utils/ids.js";import {generateReply} from "../services/gemini.js";import {reserveAiRequest} from "../middleware/requestQuota.js";
const key=u=>unwrapDataKey(u.wrappedDataKey);
const safeDecrypt=(value,k,fallback="")=>{try{return decryptText(value,k)}catch(error){console.error("CodeWise decrypt error:",error);return fallback}};
const summary=(c,k)=>({id:String(c.publicId||""),title:safeDecrypt(c.encryptedTitle,k,"New CodeWise chat"),mode:["Teacher","Explain","Hint","Interview","Debug"].includes(c.mode)?c.mode:"Teacher",preview:c.messages.at(-1)?safeDecrypt(c.messages.at(-1).encryptedText,k,"").slice(0,100):"",updatedAt:c.updatedAt});
const msg=(m,k,index)=>({id:String(m._id||`msg-${index}`),role:m.role==="model"?"model":"user",mode:["Teacher","Explain","Hint","Interview","Debug"].includes(m.mode)?m.mode:"Teacher",text:safeDecrypt(m.encryptedText,k,"This message could not be decrypted."),attachments:Array.isArray(m.attachments)?m.attachments:[],createdAt:m.createdAt});
export async function list(req,res){const k=key(req.user),cs=await Chat.find({userId:req.user._id}).sort({updatedAt:-1}).limit(100);res.json({chats:cs.map(c=>summary(c,k))})}
export async function create(req,res){const k=key(req.user),mode=["Teacher","Explain","Hint","Interview","Debug"].includes(req.body.mode)?req.body.mode:"Teacher";const c=await Chat.create({publicId:publicId("chat"),userId:req.user._id,encryptedTitle:encryptText("New CodeWise chat",k),mode,messages:[]});res.status(201).json({chat:summary(c,k)})}
export async function get(req,res){const c=await Chat.findOne({publicId:req.params.id,userId:req.user._id});if(!c)return res.status(404).json({message:"Chat not found"});const k=key(req.user);res.json({chat:{...summary(c,k),messages:c.messages.map((m,i)=>msg(m,k,i))}})}
export async function send(req,res){const c=await Chat.findOne({publicId:req.params.id,userId:req.user._id});if(!c)return res.status(404).json({message:"Chat not found"});const text=String(req.body.text||"").trim();if(!text&&!req.files?.length)return res.status(400).json({message:"Message or file required"});const quota=await reserveAiRequest(req.user._id);if(!quota.allowed){res.set({"X-RateLimit-Limit":String(quota.limit),"X-RateLimit-Remaining":"0","X-RateLimit-Reset":String(Math.floor(quota.resetAt.getTime()/1000)),"Retry-After":String(quota.resetAfterSeconds)});return res.status(429).json({message:`Daily request limit reached (${quota.limit} requests). Your limit resets in 24 hours from the start of this request window.`,requestUsage:{count:quota.count,limit:quota.limit,remaining:0,resetAt:quota.resetAt}})}if(!quota.unlimited){res.set({"X-RateLimit-Limit":String(quota.limit),"X-RateLimit-Remaining":String(quota.remaining),"X-RateLimit-Reset":String(Math.floor(quota.resetAt.getTime()/1000))});}const k=key(req.user),history=c.messages.map(m=>({role:m.role,text:safeDecrypt(m.encryptedText,k,"" )}));const files=(req.files||[]).map(f=>({buffer:f.buffer,mimeType:f.mimetype}));const attachments=(req.files||[]).map(f=>({name:f.originalname||"Attachment",mimeType:f.mimetype||"application/octet-stream",size:f.size||0}));const r=await generateReply({mode:c.mode,history,text,files});if(!r||typeof r.text!=="string")return res.status(502).json({message:"CodeWise could not generate a valid response. Please try again."});if(text||attachments.length)c.messages.push({role:"user",mode:c.mode,encryptedText:encryptText(text||`Uploaded ${attachments.length} file(s)`,k),attachments});c.messages.push({role:"model",mode:c.mode,encryptedText:encryptText(r.text,k)});if(c.messages.length<=2)c.encryptedTitle=encryptText(text?text.slice(0,55):"Uploaded CodeWise lesson",k);c.updatedAt=new Date();await c.save();res.json({message:{role:"model",mode:c.mode,text:r.text,createdAt:new Date()},chat:summary(c,k),requestUsage:quota.unlimited?{unlimited:true}:{count:quota.count,limit:quota.limit,remaining:quota.remaining,resetAt:quota.resetAt}})}
export async function remove(req,res){const r=await Chat.deleteOne({publicId:req.params.id,userId:req.user._id});if(!r.deletedCount)return res.status(404).json({message:"Chat not found"});res.json({ok:true})}
